name: CI

on: 
  push:
    branches: 
    - master

  pull_request:
    types:
    - opened
    - synchronize

jobs:
  run-elixir-tests:
    name: run-elixir-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      name: run-tests
      working-directory: ./comp6000
      run: mix test