name: CI
on: 
  push:
    branches: 
    - master
  pull_request:
    types:
    - opened
    - synchronize
jobs:
  run-elixir-tests:
    name: run-elixir-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: '23.3.4.5'
          elixir-version: '1.12.3'
          experimental-otp: true
      - run: ls
      - run: mix test